# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My School
email: mritunjayupadhyay00@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am not a blog writer. I am creating this only for checking who it works.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mupadhyay00
github_username:  mritunjayupadhyay00

# Build settings
markdown: kramdown
